### ISSUE TITLE
`fpcli ls` should return all the managed fps with different status

### ISSUE THREAD

**Issue by gitferry** [babylonchain/finality-provider#244]
Current, the command `fpcli ls` only returns fps that have been registered and running within the daemon

**Comment by choihocheol** [comment]
Hi @gitferry,
I have a question about the design of the `fp` and `fpcli` programs.
The `fp` program seems to be a structure that fetches data and stores it in the `fp` database by querying regular intervals to the BabylonChain RPC.
I’m curious why the query part in `fpcli` is coded to query fp instead of directly querying BabylonChain?

**Comment by gitferry** [comment]
Hi @choihocheol, querying BabylonChain can only show registered finality providers. By introducing `fpcli ls` we can show fps that have not been registered and we can also show whether the fps are running in the daemon
