### ISSUE TITLE
failed to register finality-provider (not found: key not found)

### ISSUE THREAD

**Issue by bert2002** [babylonchain/finality-provider#279]
Hi,
I am trying to register my finality provider according to the instructions, but it seems it cannot find the account that was created before.

fpd is running:
```
2024-04-03T08:00:40.885216Z	info	successfully connected to a remote EOTS manager	{"address": "eots:12582"}
2024-04-03T08:00:40.887063Z	info	Starting FinalityProviderApp
2024-04-03T08:00:40.887547Z	info	RPC server listening	{"address": "[::]:12581"}
2024-04-03T08:00:40.887602Z	info	Finality Provider Daemon is fully active!
```
The key was created:
```
$ fpd keys add --key-name my-finality-provider --chain-id bbn-test-3
New key for the consumer chain is created (mnemonic should be kept in a safe place for recovery):
{
    "name": "my-finality-provider",
    "address": "bbn1cptlr5xhlllq05dfkjj9rrlnc9wfsqdqv9haag",
    "mnemonic": "<hidden>"
}
```
Created the provider:
```
$ fpcli create-finality-provider --key-name my-finality-provider --chain-id bbn-test-3 --moniker '<hidden>'
{
    "babylon_pk_hex": "<hidden>",
    "btc_pk_hex": "82<hidden>",
    "description": {
        "moniker": "<hidden>"
    },
    "status": "CREATED"
}
```
and then registering fails:
```
fpcli register-finality-provider --btc-pk 82<hidden> --daemon-address 0.0.0.0:12581
[fpd] rpc error: code = NotFound desc = failed to register the finality-provider to Babylon: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account bbn1cptlr5xhlllq05dfkjj9rrlnc9wfsqdqv9haag not found: key not found
```
Key is created and available:
```
$ find .fpd/
.fpd/
.fpd/fpd.conf
.fpd/data
.fpd/data/bbolt-fpd.db
.fpd/logs
.fpd/logs/fpd.log
.fpd/keyring-test
.fpd/keyring-test/my-finality-provider.info
.fpd/keyring-test/c057f1d0d7fffe07d1a9b4a4518ff3c15c9801a0.address
.fpd/keys.lock
bash-5.1$ 
```
and in the configuration we have the same key name and key ring:
```
$ grep 'my\|test' .fpd/fpd.conf 
Key = my-finality-provider
ChainID = bbn-test-3
KeyringBackend = test
```
`fpd` was restarted after the key was created, but same error. It always times our or expires after `38s`. I can't find any timeout related to that or is it something else?

Running: `v0.1.0`

Thanks,
bert

**Comment by bert2002** [comment]
When I set the `KeyDirectory` to something where there is no key, the `fpd` dies immediately with:
```
panic: Failed to get key address: my-finality-provider.info: key not found
```
I guess that means that it does find the key and maybe just the error message is misleading. Does the validator needs to be in the active set? (because its not).

**Comment by fuleru** [comment]
I also encountered the same problem. Where is the wallet needs placed? I haven't seen the entire document.

**Comment by gitferry** [comment]
@fuleru the program finds the key from `KeyDirectory` in the `fpd.conf`

**Comment by bert2002** [comment]
> I also encountered the same problem. Where is the wallet needs placed? I haven't seen the entire document.

For me it was that the wallet did not have any funds. The error message was misleading in my case and I had to get some funds for the wallet created (in my case: `bbn1cptlr5xhlllq05dfkjj9rrlnc9wfsqdqv9haag`).

**Comment by gitferry** [comment]
@fuleru `.fpd/keyring-test/.info` should be `.fpd/keyring-test/my-finality-provider.info`

**Comment by fuleru** [comment]
yes .

babylond node is ok 


 :~# fpcli register-finality-provider --btc-pk  <hiddenbtc-pk>
[fpd] rpc error: code = Unknown desc = failed to register the finality-provider to Babylon: post failed: Post "http://localhost:26657": EOF

 :~# fpcli register-finality-provider --btc-pk  <hiddenbtc-pk>
[fpd] rpc error: code = Unknown desc = failed to register the finality-provider to Babylon: post failed: Post "http://localhost:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
 :~# fpcli register-finality-provider --btc-pk  <hiddenbtc-pk>

[fpd] rpc error: code = Unknown desc = failed to register the finality-provider to Babylon: post failed: Post "http://localhost:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
 :~# fpcli register-finality-provider --btc-pk  <hiddenbtc-pk>

[fpd] rpc error: code = Unknown desc = failed to register the finality-provider to Babylon: post failed: Post "http://localhost:26657": EOF
 :~# fpcli register-finality-provider --btc-pk  <hiddenbtc-pk>

[fpd] rpc error: code = NotFound desc = failed to register the finality-provider to Babylon: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account bbn1xxxxx not found: key not found
 
:~# fpcli register-finality-provider --btc-pk  <hiddenbtc-pk>

[fpd] rpc error: code = NotFound desc = failed to register the finality-provider to Babylon: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account bbn1xxxxx not found: key not found
 


# lsof -nP -i :26657
COMMAND      PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
babylond 2241232 root  161u  IPv4 19448070      0t0  TCP 127.0.0.1:26657->127.0.0.1:40570 (ESTABLISHED)
babylond 2241232 root  536u  IPv4 19131193      0t0  TCP 127.0.0.1:26657 (LISTEN)
babylond 2241232 root  578u  IPv4 19448074      0t0  TCP 127.0.0.1:26657->127.0.0.1:38038 (ESTABLISHED)
fpd      2528204 root    8u  IPv4 19449839      0t0  TCP 127.0.0.1:40570->127.0.0.1:26657 (ESTABLISHED)
fpd      2528204 root   14u  IPv4 19442521      0t0  TCP 127.0.0.1:38038->127.0.0.1:26657 (ESTABLISHED)



#curl -s localhost:26657/status | jq .result | jq .sync_info
{
  "latest_block_hash": "68F8793E789A8EBCD67F4A76BC46360A9E3C5E2182D822DB1E50FC53145690B2",
  "latest_app_hash": "632E9FAF1DDDD129E92754C8190584C99068EF9FEE2B66760BCFD71816BBE69C",
  "latest_block_height": "187839",
  "latest_block_time": "2024-04-16T02:10:30.441175518Z",
  "earliest_block_hash": "69DDAB992D49DCE2E63908E3BAC8E51BEAAA5430E26CC10E50EEAC0A29C65F82",
  "earliest_app_hash": "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855",
  "earliest_block_height": "1",
  "earliest_block_time": "2024-02-08T14:11:01Z",
  "catching_up": false
}

**Comment by fuleru** [comment]
> > I also encountered the same problem. Where is the wallet needs placed? I haven't seen the entire document.
> 
> For me it was that the wallet did not have any funds. The error message was misleading in my case and I had to get some funds for the wallet created (in my case: `bbn1cptlr5xhlllq05dfkjj9rrlnc9wfsqdqv9haag`).

A problem was discovered. The mnemonic generated by fpd keys add was imported into the keplr wallet through the mnemonic. The bbn address generated by fpd keys add was not the same address as the bbn address generated by fpd keys add.

**Comment by gitferry** [comment]
> [fpd] rpc error: code = NotFound desc = failed to register the finality-provider to Babylon: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account bbn1xxxxx not found: key not found

This error indicated that your account is not funded. Please request test tokens from [here](https://docs.babylonchain.io/docs/user-guides/btc-staking-testnet/getting-funds#2-request-funds-from-the-babylon-testnet-faucet)

**Comment by fuleru** [comment]
babylond node key and finality-provider key ，Do these two keys need to be the same?

**Comment by fuleru** [comment]
Babylon Full Node(babyloond)  ,EOTS Manager(eotsd )  and Finality Provider (fpd) three roles run on the same server，babyloond and fpd keys  Do you need the same？

**Comment by fuleru** [comment]
Babylon Full Node(babyloond)  ,EOTS Manager(eotsd )  and Finality Provider (fpd) three roles run on the same server.

Babylon Full Node(babyloond) is ok and  Inactive Validators .


eotsd ：

root@mybabylond:~# eotsd init
root@mybabylond:~# eotsd start
2024-04-23T16:31:57.628518Z     info    RPC server listening    {"address": "127.0.0.1:12582"}
2024-04-23T16:31:57.628671Z     info    EOTS Manager Daemon is fully active!
2024-04-23T16:33:13.865950Z     info    successfully created an EOTS key        {"key name": "mybaylondpro", "pk": "eb4cd658059e3cc38aa587fdcb910a04487119f435161da24103d5dae4137502"}

fpd:

root@mybabylond:~# fpd init
root@mybabylond:~# fpd keys add --key-name mybaylondpro --chain-id bbn-test-3
New key for the consumer chain is created (mnemonic should be kept in a safe place for recovery):
{
    "name": "mybaylondpro",
    "address": "bbn1a526e4txc3qecy69ppamehckee8zxd4v6ja2jg",
    "mnemonic": "release steel govern canal mimic gauge spring apart example sponsor joke improve patrol nominee crater hen ill chalk farm rice drive orphan undo always"
}
root@mybabylond:~# fpd start
service injective.evm.v1beta1.Msg does not have cosmos.msg.v1.service proto annotation
2024-04-23T16:32:52.360005Z     info    successfully connected to a remote EOTS manager {"address": "127.0.0.1:12582"}
2024-04-23T16:32:52.364742Z     info    Starting FinalityProviderApp
2024-04-23T16:32:52.365187Z     info    RPC server listening    {"address": "127.0.0.1:12581"}
2024-04-23T16:32:52.365263Z     info    Finality Provider Daemon is fully active!
2024-04-23T16:33:13.894187Z     info    successfully created a finality-provider        {"btc_pk": "eb4cd658059e3cc38aa587fdcb910a04487119f435161da24103d5dae4137502", "chain_pk": "PubKeySecp256k1{02EE29A313B6BDF5EBC427771B18E70B0406DAD4BD18C0FF5007F2BFE85BC26E1C}", "key_name": "mybaylondpro"}


root@mybabylond:~# fpcli cfp     --chain-id bbn-test-3     --commission 0.05     --moniker "web3passwords"  --identity "mybaylondpro"
{
    "babylon_pk_hex": "02ee29a313b6bdf5ebc427771b18e70b0406dad4bd18c0ff5007f2bfe85bc26e1c",
    "btc_pk_hex": "eb4cd658059e3cc38aa587fdcb910a04487119f435161da24103d5dae4137502",
    "description": {
        "moniker": "web3passwords",
        "identity": "mybaylondpro"
    },
    "status": "CREATED"
}
root@mybabylond:~# fpcli register-finality-provider --btc-pk eb4cd658059e3cc38aa587fdcb910a04487119f435161da24103d5dae4137502

root@mybabylond:~# netstat -nlpt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9090          0.0.0.0:*               LISTEN      1651762/babylond
tcp        0      0 127.0.0.1:26657         0.0.0.0:*               LISTEN      1651762/babylond
tcp        0      0 127.0.0.1:12582         0.0.0.0:*               LISTEN      1671560/eotsd
tcp        0      0 127.0.0.1:12581         0.0.0.0:*               LISTEN      1671606/fpd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      370087/master
tcp        0      0 0.0.0.0:4130            0.0.0.0:*               LISTEN      1662701/target/rele
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN      1651762/babylond
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      457357/sshd: /usr/s
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN      1772/dnsmasq
tcp6       0      0 :::26656                :::*                    LISTEN      1651762/babylond
tcp6       0      0 :::22                   :::*                    LISTEN      457357/sshd: /usr/s
root@mybabylond:~# lsof -nP  -i :12582  -i :26657
COMMAND      PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
babylond 1651762 root  164u  IPv4 22315004      0t0  TCP 127.0.0.1:26657 (LISTEN)
babylond 1651762 root  407u  IPv4 22357058      0t0  TCP 127.0.0.1:26657->127.0.0.1:35790 (ESTABLISHED)
eotsd    1671560 root    9u  IPv4 22356187      0t0  TCP 127.0.0.1:12582 (LISTEN)
eotsd    1671560 root   10u  IPv4 22353306      0t0  TCP 127.0.0.1:12582->127.0.0.1:45852 (ESTABLISHED)
fpd      1671606 root    9u  IPv4 22345412      0t0  TCP 127.0.0.1:45852->127.0.0.1:12582 (ESTABLISHED)
fpd      1671606 root   13u  IPv4 22355334      0t0  TCP 127.0.0.1:35790->127.0.0.1:26657 (ESTABLISHED)
root@mybabylond:~#

root@mybabylond:~# fpcli register-finality-provider --btc-pk eb4cd658059e3cc38aa587fdcb910a04487119f435161da24103d5dae4137502
[fpd] rpc error: code = NotFound desc = failed to register the finality-provider to Babylon: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account bbn1a526e4txc3qecy69ppamehckee8zxd4v6ja2jg not found: key not found

#fpcli register-finality-provider --btc-pk eb4cd658059e3cc38aa587fdcb910a04487119f435161da24103d5dae4137502
[fpd] rpc error: code = NotFound desc = failed to register the finality-provider to Babylon: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account bbn1a526e4txc3qecy69ppamehckee8zxd4v6ja2jg not found: key not found


I don't know where the problem is?

I have already referred
https://docs.babylonchain.io/docs/user-guides/btc-staking-testnet/getting-funds#2-request-funds-from-the-babylon-testnet-faucet

Babylon Full Node(babyloond) keys no problem.

**Comment by gitferry** [comment]
The relevant babylon account that `fpd` is using is not funded

**Comment by fuleru** [comment]
> The relevant babylon account that `fpd` is using is not funded

There is a problem here. Use babylond to import the mnemonic generated by fpd. The bbn address generated is different from the bbn address generated by fpd. I wonder if there is any problem?
