### ISSUE TITLE
Can a FP unbound the stake, deregister and register again for a different consumer chain?

### ISSUE THREAD

**Issue by bap2pecs** [babylonchain/finality-provider#356]
I'd vote to not allow this to avoid some edge case attack scenarios. wdyt?

**Comment by SebastianElvis** [comment]
This is not allowed in Babylon indeed. The reason is that if this FP is slashed for some reason, it will get slashed on all consumer chains that it has registered to since its SK is leaked. This is not desired. 

In fact, Babylon dose not allow a FP to de-register. This means once a FP is registered on a consumer, it will always be there and this FP cannot be moved to other consumers.
